let setting = [
    "Средневековый",
    "Космический",
    "Фентези",
    "Реалистичный",
    "Стимпанк",
    "Киберпанк",
    "Дизельранк",
    "Ядерпанк",
];
let genre = [
    "Экшн",
    "РПГ",
    "Пазл",
    "Квест",
    "Эдвенчур",
    "Слэшер",
    "Гонки",
    "Платформер",
    "Стелс",
    "Аркада",
    "Выживач",
    "Спорт",
    "Симулятор",
    "Шутер",
    "Хорор",
    "Файтинг",
    "Rogue-like",
    "Строительчтво",
    "Экономическая",
    "Стратегия",
    "Тауер-дефенс",
    "Карточная",
    "Логическая",
    "Постапок"
];
let special = [
    "без механик стрельбы",
    "и ты не можешь сделать это в одиночку",
    "без текста вовсе",
    "и можно пройти одной рукой",
    "Game must be wildly different after the second playgrough",
    "Sounds are core mechanic",
    "The title must be a pun",
    "All ui must be diagetic",
    "Game must incorperate procedural generation",
    "Running out of power",
    "",
];

let limits = [setting, genre, special]